name: Build and Deploy Container Image

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  GHCR_USERNAME: ${{ github.repository_owner }}
  GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Docker build and push job removed as Docker is not needed.
